[package]
name = "msf-zoe"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.1.7"
aws-sdk-s3 = "1.19.0"
chrono = "0.4.41"
dotenvy = "0.15"
rocket = "0.5.1"
rusqlite = { version = "0.37.0", features = ["bundled"] }
tokio = { version = "1.0", features = ["full"] }
